name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - name: setup git auth
        env:
          email: 'brsilvacarlos@gmail.com'
          username: 'brsilvacarlos'
        run: |
          git config --global credential.helper store
          echo "https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com" > ~/.git-credentials
          git config --global user.email $email
          git config --global user.name $username
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: build
        run: |
          npm i
          NODE_ENV=production npm run build
      - name: deploy to gh-pages
        run: |
          cd dist
          git init
          git add -A
          git commit -m "🚀 Deploy id ${GITHUB_RUN_ID}"
          git push -f gh-pages